language: node_js

os:
  - linux

install:
  - echo themezv.ru $ASERVER_TRAVIS_PUB >> $HOME/.ssh/known_hosts

node_js:
- '8'

cache: yarn

jobs:
  include:
    - stage: install
      script:
      - cat $HOME/.ssh/known_hosts
      - yarn
      - yarn lint
      - yarn deploy-stage
