language: node_js

os:
  - linux

node_js:
  - '8.9.4'

cache: yarn

branches:
  only:
  - master
  - develop
  - deploy
  - /^(?i:release)-.*$/

script:
  - yarn
  - yarn lint


deploy:
  - skip_cleanup: true
  # deploy develop to the staging environment
  - provider: script
    script:
      - ls
      - echo $type
      - yarn
      - yarn deploy-stage
    on:
      branch: deploy
  # deploy master to production
  - provider: script
    script:
      - yarn
      - yarn deploy-prod
    on:
      branch: master

git:
  depth: false
