language: node_js

os:
  - linux

node_js:
  - '8.9.4'

cache: yarn

branches:
  only:
  - master
  - develop
  - deploy
  - /^(?i:release)-.*$/

script:
  - yarn
  - yarn lint

jobs:
  include:
    - if: branch = master
    script:
      - yarn deploy-stage

jobs:
  include:
    - if: branch = develop
    script:
      - yarn deploy-stage


git:
  depth: false
