language: node_js

os:
  - linux

node_js:
- '8.9.4'

cache: yarn

script:
  - yarn
  - yarn lint


deploy:
  - skip_cleanup: true
  - provider: script
    script: yarn deploy-stage

  - provider: script
    script: yarn deploy-prod
    on:
      branch: master
