language: node_js

os:
  - linux

node_js:
- '8.9.4'

cache: yarn

script:
  - yarn
  - yarn lint


deploy:
  skip_cleanup: true
  # deploy develop to the staging environment
  - provider: script
    script: yarn deploy-stage
#    on:
#      branch: develop
  # deploy master to production
  - provider: script
    script: yarn deploy-prod
    on:
      branch: master
