const types =  {
    LIDERLIST_REQUEST: '@@game/LIDERLIST_REQUEST',
    LIDERLIST_SUCCESS: '@@game/LIDERLIST_SUCCESS',
    LIDERLIST_ERROR: '@@game/LIDERLIST_ERROR',     
    CONNECT_TO_GAME_REQUEST: '@@ws/CONNECT_TO_GAME_REQUEST',  
    CONNECT_TO_GAME_SUCCESS: '@@ws/CONNECT_TO_GAME_SUCCESS',  
    GET_MEM_PAIR_REQUEST: '@@ws/GET_MEM_PAIR_REQUEST',
    GET_MEM_PAIR_SUCCESS: '@@ws/GET_MEM_PAIR_SUCCESS',
    CHOOSE_MEM_REQUEST: '@@ws/CHOOSE_MEM_REQUEST',
    CHOOSE_MEM_SUCCESS: '@@ws/CHOOSE_MEM_SUCCESS',  
    LEAVE_FROM_GAME_SUCCESS: '@@ws/LEAVE_FROM_GAME_SUCCESS',
    LEAVE_FROM_GAME_REQUEST: '@@ws/LEAVE_FROM_GAME_REQUEST',
    PAIR_WINNER: '@@ws/PAIR_WINNER',
    NEW_PAIR: '@@ws/NEW_PAIR',
};

export default types;