const types =  {
    LOGIN_CHECK_REQUEST: '@@user/LOGIN_CHECK_REQUEST',
    LOGIN_CHECK_SUCCESS: '@@user/LOGIN_CHECK_SUCCESS',
    LOGIN_CHECK_ERROR: '@@user/LOGIN_CHECK_ERROR',
    REGISTER_REQUEST: '@@user/REGISTER_REQUEST',
    REGISTER_SUCCESS: '@@user/REGISTER_SUCCESS',
    REGISTER_ERROR: '@@user/REGISTER_ERROR',    
    LOGIN_REQUEST: '@@user/LOGIN_REQUEST',
    LOGIN_SUCCESS: '@@user/LOGIN_SUCCESS',
    LOGIN_ERROR: '@@user/LOGIN_ERROR',    
};

export default types;