const types = {
    CONNECT_TO_GAME_REQUEST: '@@rush/CONNECT_TO_GAME_REQUEST',
    CONNECT_TO_GAME_SUCCESS: '@@rush/CONNECT_TO_GAME_SUCCESS',
    CONNECT_TO_GAME_ERROR: '@@rush/CONNECT_TO_GAME_ERROR',

    CHOOSE_MEM_REQUEST: '@@rush/CHOOSE_MEM_REQUEST',
    CHOOSE_MEM_SUCCESS: '@@rush/CHOOSE_MEM_SUCCESS',
    CHOOSE_MEM_ERROR: '@@rush/CHOOSE_MEM_ERROR',

    LEAVE_FROM_GAME_SUCCESS: '@@rush/LEAVE_FROM_GAME_SUCCESS',
    LEAVE_FROM_GAME_REQUEST: '@@rush/LEAVE_FROM_GAME_REQUEST',
    LEAVE_FROM_GAME_ERROR: '@@rush/LEAVE_FROM_GAME_ERROR'
};

export default types;
